### ISSUE TITLE
BUG: [id: 804] apa yang ada didalam laut selain ikan?

### ISSUE THREAD

**Issue by Velliz** [yulrizka/fam100#2]
I had answers: karang 
but the game has automatic mark i has already answer 2 right questions:
1. (36) karang ✓
2. (32) gurita ✓
but i never type gurita. please add fix for it. 

Thanks. :D

**Comment by citos29** [comment]
nice post brotha!

we'll working on it ASAP!
thanks a lot.

Citos
Fam100 Support Team.

**Comment by Velliz** [comment]
seems already fixed. 
i close this issue.
